root = "."
tmp_dir = ".air"

[build]
cmd = "go build -o .air/server ./cmd/server"
bin = ".air/server"
delay = 100
stop_on_error = true

[log]
time = true

[watch]
include_dir = [
  "cmd",
  "internal",
  ".air.toml",
  "go.mod",
  "go.sum",
]
exclude_dir = [
  ".git",
  ".air",
  "bin",
  "out",
  "dist",
  "vendor",
]

