openapi: 3.1.0
info:
  title: Go Todo API
  version: 0.1.0
servers:
  - url: http://localhost:8080
paths:
  /healthz:
    get:
      responses:
        '200': { description: OK }
  /todos/:
    get:
      parameters:
        - in: query
          name: limit
          schema: { type: integer, minimum: 1, maximum: 100, default: 20 }
          description: Max number of items to return (1-100)
        - in: query
          name: offset
          schema: { type: integer, minimum: 0, default: 0 }
          description: Number of items to skip before starting to collect the result set
      responses:
        '200':
          description: List todos
          content:
            application/json:
              schema:
                type: array
                items: { $ref: '#/components/schemas/Todo' }
        '500':
          description: Error
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Error' }
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/CreateTodoRequest' }
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Todo' }
        '400': { description: Bad request, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '415': { description: Unsupported Media Type, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '413': { description: Payload too large, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '500': { description: Error, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
  /todos/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/Todo' } } } }
        '404': { description: Not found, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '500': { description: Error, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
    patch:
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/UpdateTodoRequest' }
      responses:
        '200': { description: OK, content: { application/json: { schema: { $ref: '#/components/schemas/Todo' } } } }
        '400': { description: Bad request, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '404': { description: Not found, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '415': { description: Unsupported Media Type, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '413': { description: Payload too large, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '500': { description: Error, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
    delete:
      parameters:
        - in: path
          name: id
          required: true
          schema: { type: string }
      responses:
        '204': { description: No content }
        '404': { description: Not found, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }
        '500': { description: Error, content: { application/json: { schema: { $ref: '#/components/schemas/Error' } } } }

components:
  schemas:
    Error:
      type: object
      properties:
        code: { type: string }
        string: { type: string }
        message: { type: string }
        status: { type: integer }
        request_id: { type: string }
      required: [code, string, message, status]
    Todo:
      type: object
      properties:
        id: { type: string }
        title: { type: string }
        completed: { type: boolean }
        created_at: { type: string, format: date-time }
        updated_at: { type: string, format: date-time }
      required: [id, title, completed, created_at, updated_at]
    CreateTodoRequest:
      type: object
      properties:
        title: { type: string }
      required: [title]
    UpdateTodoRequest:
      type: object
      properties:
        title: { type: string }
        completed: { type: boolean }

